server:
   port: 8003
spring:
    application:
      name: log-queue
    kafka:
      bootstrap-servers: 192.168.140.129:9092
      consumer:
         group-id: group1
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/